### ISSUE TITLE
Info renders over Bossbar

### ISSUE THREAD

**Issue by Precizne** [Prismwork/Hudium#10]
The coordinates and direction info are rendered at the same place as the bossbar. I don't know how it is displayed on different resolutions and gui scales but here are my settings: 1366x768 fullscreen (gui scale 2).
![2022-06-28_14 14 11](https://user-images.githubusercontent.com/63221503/176137274-e82ab51a-13e0-4ba1-990a-fd10fb8f6c42.png)

**Comment by moechakucha** [comment]
I had envisioned this situation a long time ago, but never got around to fixing it :D
Will be fixed in 1.4.0

**Comment by Precizne** [comment]
A secondary problem arises with the current fix.
If too many bosses are spawned, the coordinate and direction info can appear a lot lower than the lowest bossbar and can possibly go out of screen space.
This also varies across different resolutions, gui scales and fullscreen vs windowed.
![2022-06-28_18 21 00](https://user-images.githubusercontent.com/63221503/176183086-634cabe9-036f-4287-a629-59939c2dd541.png)
![2022-06-28_18 20 52](https://user-images.githubusercontent.com/63221503/176183186-cbb5dc58-5a7d-4e06-874a-a24319bbdaf1.png)
![2022-06-28_18 20 34](https://user-images.githubusercontent.com/63221503/176183220-8a7d36cb-4782-4d54-9eb7-0acc638a3eca.png)
![2022-06-28_18 20 21](https://user-images.githubusercontent.com/63221503/176183235-1192dace-a825-412a-b958-656a26ef04d9.png)

**Comment by moechakucha** [comment]
oops

**Comment by Precizne** [comment]
I tried an alternate fix.
In the presence of a bossbar, the coordinate and direction info get shifted to the top of the hotbar.
(need to change the y value a bit for the creative mode)
![2022-06-28_19 15 14](https://user-images.githubusercontent.com/63221503/176195580-04a89f9b-ba23-405f-b050-5f472a83026a.png)
![2022-06-28_19 15 03](https://user-images.githubusercontent.com/63221503/176195608-cc6935c0-ad7c-4b7c-9a64-4331f1d4d550.png)
![2022-06-28_19 14 45](https://user-images.githubusercontent.com/63221503/176195616-5595738f-dc92-499a-a221-a79be271045c.png)

**Comment by moechakucha** [comment]
I haven't thought of solving the problem in such way, but it looks not bad anyway.

**Comment by Precizne** [comment]
Yeah, I do agree it is not the best solution and is a pretty different approach than normal. So, we keep this approach aside till we come up with a better one to solve the problem?

**Comment by moechakucha** [comment]
I think so, while I'll keep trying to get my idea work flawlessly.
Until then, moving this down should be the best solution.

**Comment by moechakucha** [comment]
Polished the logic of the detection of boss bars in 1.4.1, now should not have any issues.

**Comment by moechakucha** [comment]
But I see that your feature is also implemented so maybe as a configuration entry?

**Comment by Precizne** [comment]
Yeah sure, I am going to change it a bit so it I can PR it.
