### ISSUE TITLE
[FEATURE REQUEST] RPG hud

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Prismwork/Hudium#20]
RPG hud style themes, and configuration.

**Comment by moechakucha** [comment]
wdym?

**Comment by moechakucha** [comment]
i'd like to see features like changeable themes being implemented tho

**Comment by DanMeadWasTaken** [comment]
> wdym?

RPG hud adds in some themed huds, for both looked at entities, as well as health/armor n such. I'm tired rn, so I can't go into full details, but just search up RPG hud mod

**Comment by DanMeadWasTaken** [comment]
So, I was thinking about this again the other day, and figured I'd clarify. Basically different themes/styles. Although i had realized one thing that RPG hud lacks which is much needed- Mod compatibility like, Like with apple skin, victus, health overlay, sprint o' meter and so on.

**Comment by DanMeadWasTaken** [comment]
Funilly enough, I've now found a mod called EssentialGUI that hits almost all the points i needed/wanted.
