### ISSUE TITLE
Add information of required mining level

### ISSUE THREAD

**Issue by lospejos** [Prismwork/Hudium#3]
The `WTHIT` (https://modrinth.com/mod/wthit) mod with `cAn i MiNe thIS bLOCk?` (https://modrinth.com/mod/can-i-mine-this-block) installed together has a feature to display required mining level and which mod provides pointed ore, see screenshot below:

![image](https://user-images.githubusercontent.com/4608475/174433903-0a8b8f30-7ff6-4fa0-8d56-29b92dcf3528.png)

If it is possible, if it is applicable and if it is not done yet, please add such a feature. Thanks.

**Comment by moechakucha** [comment]
of course i guess
